<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 3.0//EN">
<!--Converted with LaTeX2HTML 96.1 (Feb 5, 1996) by Nikos Drakos (nikos@cbl.leeds.ac.uk), CBLU, University of Leeds -->
<HTML>
<HEAD>
<TITLE>1.10.4 Thin Ice</TITLE>
<META NAME="description" CONTENT="1.10.4 Thin Ice">
<META NAME="keywords" CONTENT="ext">
<META NAME="resource-type" CONTENT="document">
<META NAME="distribution" CONTENT="global">
<LINK REL=STYLESHEET HREF="ext.css">
</HEAD>
<BODY LANG="EN">
 <A NAME="tex2html376" HREF="node17.html"><IMG WIDTH=37 HEIGHT=24 ALIGN=BOTTOM ALT="next" SRC="../icons/next_motif.gif" BORDER=0></A> <A NAME="tex2html374" HREF="node12.html"><IMG WIDTH=26 HEIGHT=24 ALIGN=BOTTOM ALT="up" SRC="../icons/up_motif.gif" BORDER=0></A> <A NAME="tex2html368" HREF="node15.html"><IMG WIDTH=63 HEIGHT=24 ALIGN=BOTTOM ALT="previous" SRC="../icons/previous_motif.gif" BORDER=0></A> <A NAME="tex2html378" HREF="node1.html"><IMG WIDTH=65 HEIGHT=24 ALIGN=BOTTOM ALT="contents" SRC="../icons/contents_motif.gif" BORDER=0></A> <A NAME="tex2html379" HREF="node38.html"><IMG WIDTH=43 HEIGHT=24 ALIGN=BOTTOM ALT="index" SRC="../icons/index_motif.gif" BORDER=0></A> <BR>
<B> Next:</B> <A NAME="tex2html377" HREF="node17.html">1.10.5 NULL Pointers</A>
<B>Up:</B> <A NAME="tex2html375" HREF="node12.html">1.10 Reference Counts</A>
<B> Previous:</B> <A NAME="tex2html369" HREF="node15.html">1.10.3 Ownership Rules</A>
<BR><HR><P>
<H2><A NAME="SECTION002104000000000000000">1.10.4 Thin Ice</A></H2>
<P>
There are a few situations where seemingly harmless use of a borrowed
reference can lead to problems.  These all have to do with implicit
invocations of the interpreter, which can cause the owner of a
reference to dispose of it.
<P>
The first and most important case to know about is using
<CODE>Py_DECREF()</CODE> on an unrelated object while borrowing a reference
to a list item.  For instance:
<P>
<PRE>bug(PyObject *list) {
    PyObject *item = PyList_GetItem(list, 0);
    PyList_SetItem(list, 1, PyInt_FromLong(0L));
    PyObject_Print(item, stdout, 0); /* BUG! */
}</PRE>
<P>
This function first borrows a reference to <CODE>list[0]</CODE>, then
replaces <CODE>list[1]</CODE> with the value <CODE>0</CODE>, and finally prints
the borrowed reference.  Looks harmless, right?  But it's not!
<P>
Let's follow the control flow into <CODE>PyList_SetItem()</CODE>.  The list
owns references to all its items, so when item 1 is replaced, it has
to dispose of the original item 1.  Now let's suppose the original
item 1 was an instance of a user-defined class, and let's further
suppose that the class defined a <CODE>__del__()</CODE> method.  If this
class instance has a reference count of 1, disposing of it will call
its <CODE>__del__()</CODE> method.
<P>
Since it is written in Python, the <CODE>__del__()</CODE> method can execute
arbitrary Python code.  Could it perhaps do something to invalidate
the reference to <CODE>item</CODE> in <CODE>bug()</CODE>?  You bet!  Assuming that
the list passed into <CODE>bug()</CODE> is accessible to the
<CODE>__del__()</CODE> method, it could execute a statement to the effect of
<CODE>del list[0]</CODE>, and assuming this was the last reference to that
object, it would free the memory associated with it, thereby
invalidating <CODE>item</CODE>.
<P>
The solution, once you know the source of the problem, is easy:
temporarily increment the reference count.  The correct version of the
function reads:
<P>
<PRE>no_bug(PyObject *list) {
    PyObject *item = PyList_GetItem(list, 0);
    Py_INCREF(item);
    PyList_SetItem(list, 1, PyInt_FromLong(0L));
    PyObject_Print(item, stdout, 0);
    Py_DECREF(item);
}</PRE>
<P>
This is a true story.  An older version of Python contained variants
of this bug and someone spent a considerable amount of time in a C
debugger to figure out why his <CODE>__del__()</CODE> methods would fail...
<P>
The second case of problems with a borrowed reference is a variant
involving threads.  Normally, multiple threads in the Python
interpreter can't get in each other's way, because there is a global
lock protecting Python's entire object space.  However, it is possible
to temporarily release this lock using the macro
<CODE>Py_BEGIN_ALLOW_THREADS</CODE>, and to re-acquire it using
<CODE>Py_END_ALLOW_THREADS</CODE>.  This is common around blocking I/O
calls, to let other threads use the CPU while waiting for the I/O to
complete.  Obviously, the following function has the same problem as
the previous one:
<P>
<PRE>bug(PyObject *list) {
    PyObject *item = PyList_GetItem(list, 0);
    Py_BEGIN_ALLOW_THREADS
    ...some blocking I/O call...
    Py_END_ALLOW_THREADS
    PyObject_Print(item, stdout, 0); /* BUG! */
}</PRE>
<P>
<HR><A NAME="tex2html376" HREF="node17.html"><IMG WIDTH=37 HEIGHT=24 ALIGN=BOTTOM ALT="next" SRC="../icons/next_motif.gif" BORDER=0></A> <A NAME="tex2html374" HREF="node12.html"><IMG WIDTH=26 HEIGHT=24 ALIGN=BOTTOM ALT="up" SRC="../icons/up_motif.gif" BORDER=0></A> <A NAME="tex2html368" HREF="node15.html"><IMG WIDTH=63 HEIGHT=24 ALIGN=BOTTOM ALT="previous" SRC="../icons/previous_motif.gif" BORDER=0></A> <A NAME="tex2html378" HREF="node1.html"><IMG WIDTH=65 HEIGHT=24 ALIGN=BOTTOM ALT="contents" SRC="../icons/contents_motif.gif" BORDER=0></A> <A NAME="tex2html379" HREF="node38.html"><IMG WIDTH=43 HEIGHT=24 ALIGN=BOTTOM ALT="index" SRC="../icons/index_motif.gif" BORDER=0></A> <BR>
<B> Next:</B> <A NAME="tex2html377" HREF="node17.html">1.10.5 NULL Pointers</A>
<B>Up:</B> <A NAME="tex2html375" HREF="node12.html">1.10 Reference Counts</A>
<B> Previous:</B> <A NAME="tex2html369" HREF="node15.html">1.10.3 Ownership Rules</A>
<P><ADDRESS>
guido@cnri.reston.va.us
</ADDRESS>
</BODY>
</HTML>
